name: beacon

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      rev:
        description: Commit hash (full or shortened) or tag or branch name
        type: string
        required: true
        default: main
      ghc:
        description: Compiler version
        type: string
        required: false

jobs:
  beacon:
    name: Run beacon
    runs-on: ubuntu-latest

    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
        with:
          extra-conf: accept-flake-config = true

      - run: nix build github:${{ github.repository }}/${{ github.sha }} --out-link beacon

      - run: ./beacon build --rev ${{ inputs.rev }} ${{ inputs.ghc != null && format('--ghc {0}', inputs.ghc) || '' }}
