name: beacon

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      rev:
        description: Commit hash (full or shortened) or tag or branch name
        type: string
        required: true
        default: main
      ghc:
        description: Compiler version
        type: string
        required: false

jobs:
  beacon:
    defaults:
      run:
        shell: ${{ github.workspace }}/scripts/acquire-lock.sh

    name: Run beacon
    runs-on: self-hosted

    steps:
      - run: |
          printenv
          ls -l /
          ls -l /mnt/
          ls -l /mnt/beacon-data

      - run: |
          nix build github:${{ github.repository }}/${{ github.sha }}

      - run: |
          result/bin/beacon --data-dir $STATE_DIRECTORY/beacon-data build --rev ${{ inputs.rev }}
