name: beacon

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      rev:
        description: Commit hash (full or shortened) or tag or branch name
        type: string
        required: true
        default: main
      ghc:
        description: Compiler version
        type: string
        required: false

jobs:
  beacon:
    name: Run beacon
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27

      - run: nix run github:${{ github.repository }}/${{ github.sha }} -- build --rev ${{ inputs.rev }} ${{ inputs.ghc != null && format('--ghc {0}', inputs.ghc) || '' }}
