name: beacon

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      rev:
        description: Commit hash (full or shortened) or tag or branch name
        type: string
        required: true
        default: main
      ghc:
        description: Compiler version
        type: string
        required: false

jobs:
  beacon:
    name: Run beacon
    runs-on: self-hosted

    steps:
      # - uses: actions/cache@v4
      #   with:
      #     path: /nix
      #     key: 1

      # - uses: cachix/install-nix-action@v27
      #   with:
      #     github_access_token: ${{ secrets.GITHUB_TOKEN }}
      #     extra_nix_config: |
      #       accept-flake-config = true
      #       allow-import-from-derivation = true
      #       extra-substituters = https://cache.iog.io
      #       extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

      - uses: DeterminateSystems/nix-installer-action@v14
        with:
          extra-conf: |
            accept-flake-config = true
            allow-import-from-derivation = true
            extra-substituters = https://cache.iog.io
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - run: |
          nix build github:${{ github.repository }}/${{ github.sha }}

      - run: |
          printenv
          ls -l /

      - run: |
          result/bin/beacon --data-dir /beacon-data build --rev ${{ inputs.rev }}
