name: beacon

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      rev:
        description: Commit hash (full or shortened) or tag or branch name
        type: string
        required: true
        default: main
      ghc:
        description: Compiler version
        type: string
        required: false
      name:
        description: Chain fragment name to run on
        type: string
        required: true

jobs:
  beacon:
    name: Run beacon
    runs-on: self-hosted
    env:
      LOCKFILE: /tmp/workbench.lock
      LOCK_TIMEOUT: "3600" # seconds (1 hour)

    steps:
      - run: printenv

      - run: |
          curl -v -s -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -o /mnt/beacon-data/temp.curl.json https://api.github.com/repos/IntersectMBO/ouroboros-consensus/commits/main

      - run: |
          nix build github:${{ github.repository }}/${{ github.sha }} -o result
          echo $PWD/result/bin >> $GITHUB_PATH

      - run: beacon --data-dir $BEACON_DATA build --rev ${{ inputs.rev }}

      - run: |
          echo "Waiting for lock on $LOCKFILE..."
          flock --wait "$TIMEOUT_SECS" "$LOCKFILE" --
            beacon --data-dir $BEACON_DATA run --rev ${{ inputs.rev }} --name ${{ inputs.name }}
