name: beacon

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      rev:
        description: Commit hash (full or shortened) or tag or branch name
        type: string
        required: true
        default: main
      ghc:
        description: Compiler version
        type: string
        required: false

jobs:
  beacon:
    name: Run beacon
    runs-on: self-hosted

    steps:
      # - uses: DeterminateSystems/nix-installer-action@v14
      #   with:
      #     extra-conf: |
      #       accept-flake-config = true
      #       allow-import-from-derivation = true
      #       extra-substituters = https://cache.iog.io
      #       extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
      #
      # - uses: DeterminateSystems/magic-nix-cache-action@v8

      - run: |
          printenv
          ls -l /
          ls -l /mnt/
          ls -l /mnt/beacon-data

      - run: |
          nix build github:${{ github.repository }}/${{ github.sha }}

      - run: |
          result/bin/beacon --data-dir /mnt/beacon-data build --rev ${{ inputs.rev }}
